Repository KwonDae/ImagePicker, pull requests merged in 2024-01, with the labels that each got.

#4 Android 포토피커 로직 구현 및 UI 적용
  composeApp/src/androidMain/kotlin/org/moneyking/imagepicker/Application.kt
  composeApp/src/androidMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/App.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/DummyImageList.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/component/ImageCard.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
  composeApp/src/desktopMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
  composeApp/src/iosMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
Labels: enhancement, design

#7 iOS 포토피커 로직 구현
  composeApp/src/androidMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/App.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/component/ImageCard.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
  composeApp/src/desktopMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
  composeApp/src/iosMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
Labels: enhancement

#6 String Resource 국제화 적용
  composeApp/build.gradle.kts
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/App.kt
  composeApp/src/commonMain/resources/MR/base/strings.xml
  composeApp/src/commonMain/resources/MR/en/strings.xml
  iosApp/iosApp/Info.plist
Labels: enhancement, design

#8 SinglePhotoPicker 이슈 해결
  composeApp/src/androidMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
Labels: bug

#9 화면 가로 모드 대응
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/App.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/component/ImageCard.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/util/extension/Modifier.kt
Labels: design

#10 Decompose 라이브러리 적용
  composeApp/build.gradle.kts
  composeApp/src/androidMain/kotlin/org/moneyking/imagepicker/MainActivity.kt
  composeApp/src/androidMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/App.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/component/ImageCard.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/navigation/DetailScreenComponent.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/navigation/MainScreenComponent.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/navigation/MainScreenEvent.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/navigation/RootComponent.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/screen/DetailScreen.kt
  composeApp/src/commonMain/kotlin/org/moneyking/imagepicker/screen/MainScreen.kt
  composeApp/src/commonMain/resources/MR/base/strings.xml
  composeApp/src/commonMain/resources/MR/en/strings.xml
  composeApp/src/desktopMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
  composeApp/src/iosMain/kotlin/org/moneyking/imagepicker/MainViewController.kt
  composeApp/src/iosMain/kotlin/org/moneyking/imagepicker/launcher/ImagePickerLauncher.kt
  gradle/libs.versions.toml
  iosApp/iosApp/ContentView.swift
Labels: enhancement, design, refactoring
